//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_management_system.Principal
{


    public partial class CreateNotification
    {
        protected global::System.Web.UI.WebControls.TextBox Notification_Title;
        protected global::System.Web.UI.WebControls.TextBox Notification_Desciption;
        protected global::System.Web.UI.WebControls.DropDownList To;
    }
}
