//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_management_system.Co_ordinator
{


    public partial class DashBoard
    {
        protected global::System.Web.UI.WebControls.Label tacherCount;
        protected global::System.Web.UI.WebControls.Label DepartmentCount;
    }
}
