//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_management_system.Co_ordinator
{


    public partial class StudentAccountCreate
    {
        protected global::System.Web.UI.WebControls.TextBox SubjectName;
        protected global::System.Web.UI.WebControls.TextBox email;
        protected global::System.Web.UI.WebControls.TextBox number;
        protected global::System.Web.UI.WebControls.TextBox department;
        protected global::System.Web.UI.WebControls.TextBox course;
        protected global::System.Web.UI.WebControls.DropDownList Year;
        protected global::System.Web.UI.WebControls.TextBox sessionYear;
        protected global::System.Web.UI.WebControls.TextBox Password;
        protected global::System.Web.UI.WebControls.DropDownList Semister;
    }
}
