//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_management_system.Co_ordinator
{


    public partial class SubjectCreate
    {
        protected global::System.Web.UI.WebControls.TextBox course;
        protected global::System.Web.UI.WebControls.TextBox Department;
        protected global::System.Web.UI.WebControls.TextBox SubjectName;
        protected global::System.Web.UI.WebControls.TextBox SubjectTeacher;
        protected global::System.Web.UI.WebControls.TextBox Year;
        protected global::System.Web.UI.WebControls.TextBox Semister;
    }
}
