//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_management_system.HOD
{


    public partial class teacherDetails
    {
        protected global::System.Web.UI.WebControls.TextBox Name;
        protected global::System.Web.UI.WebControls.TextBox EmailID;
        protected global::System.Web.UI.WebControls.TextBox Role;
        protected global::System.Web.UI.WebControls.TextBox DepartmentName;
        protected global::System.Web.UI.WebControls.TextBox permission;
    }
}
